connect / as sysdba

drop user usr_01          cascade;
drop user org_data        cascade;
drop role org_data_admin;

create user usr_01   identified by secretGarden default tablespace data temporary tablespace temp quota unlimited on data;
create user org_data identified by secretGarden default tablespace data temporary tablespace temp quota unlimited on data;
create role org_data_admin;


grant
   create session,
   create table,
   create procedure,
   create sequence
to
   org_data;

grant execute on dbms_random to org_data;

grant
   create session
to
   usr_01;


connect org_data/secretGarden

create table tab_p (
   id   integer          generated by default on null as identity,
   tx   varchar2(20)     not null,
   nm   number               null,
   --
   constraint tab_p_pk primary key(id),
   constraint tab_p_uq unique     (tx)
);


create table tab_c (
   id_p                not null,
   val_1  varchar2(10) not null,
   val_2  number       not null,
   --
   constraint tab_c_fk foreign key (id_p) references tab_p
);


insert into tab_p (tx, nm) values ('five' , 5);
insert into tab_p (tx, nm) values ('four' , 4);
insert into tab_p (tx, nm) values ('seven', 7);
insert into tab_p (tx, nm) values ('eight', 8);

create package modif_tab as

    procedure insert_c (tx_ varchar2, val_1_ varchar2, val_2_ number);

end modif_tab;
/


create package body modif_tab as

    procedure insert_c (tx_ varchar2, val_1_ varchar2, val_2_ number) is
    begin

        insert into tab_c(id_p, val_1, val_2)
        select
           id,
           val_1_,
           val_2_
        from
           tab_p
        where
           tx = tx_;

    end insert_c;

end modif_tab;
/


begin
   modif_tab.insert_c('four' , 'A',  5.1);
   modif_tab.insert_c('seven', 'B', 24.7);
   modif_tab.insert_c('five' , 'C',  8.2);
end;
/

create package usr_interface as
   procedure insert_random_data;
end;
/

create package body usr_interface as
   procedure insert_random_data is
      tx_  varchar2(20);
   begin
      tx_ := dbms_random.string('a', dbms_random.value(1, 20));
      insert into tab_p (tx, nm) values (tx_, trunc(dbms_random.value(0, 1000),2));

      modif_tab.insert_c(tx_, dbms_random.string('x', dbms_random.value(1,10)), trunc(dbms_random.value(1, 100000), 30));

   end insert_random_data;
end;
/

begin
   dbms_random.seed(1);
   usr_interface.insert_random_data;
   usr_interface.insert_random_data;
   usr_interface.insert_random_data;
end;
/

grant execute on usr_interface to usr_01;

connect usr_01/secretGarden

-- ORA-00942: table or view does not exist
--
-- select * from org_data.tab_c;
-- select * from org_data.tab_p;

begin
   dbms_random.seed(2);
   org_data.usr_interface.insert_random_data;
   org_data.usr_interface.insert_random_data;
   org_data.usr_interface.insert_random_data;
end;
/

connect org_data/secretGarden

select * from org_data.tab_c;
select * from org_data.tab_p;
